### ISSUE TITLE
show the "thought process" in the slack thread

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/practical-llms#31]
for debugging and progress tracking purposes show the steps and tools that the agent is using to answer the question

**Comment by johnnykfeng** [comment]
My plan is to create another version of the bot, maybe called @SherpaDebug and have it function the same manner, except return the internal messages as part of the response e.g. thought process, retrieved documents, tools, etc.

**Comment by amirfz** [comment]
@johnnykfeng my suggestion is to show parts of the thought process through sherpa itself. I don't think a separate bot would be useful (unless we can do something like @sherpa -verbose <question>). I think what we can do is to only show the "command" part of the ReAct framework to indicate to the user that sherpa is looking for information even if it is taking a bit longer to synthesize everything. sorta the ideal outcome is going to be:

USER: @sherpa answer this question
SHERPA: I need to search on google for this keyword (command 1)
SHERPA: I need to search through LangChain documentation for this info (command 2)
SHERPA: Here is what i found (fixed message): <answer>

in the `-verbose` version, if possible at all, we could also include the observations as separate messages

this way it is possible to see what information it is looking for (for debugging purposes but also for better UX).

**Comment by johnnykfeng** [comment]
@amirfz Okay, calling it @sherpa -verbose is basically the same idea I had in mind. It wouldn't be another bot per se, just some way to change the output mode. The template you made is helpful in visualizing what it should look like. I will make a simple plain text version first, then we can work on formatting the debugging messages in a different font or color afterwards, or it can be a different message altogether.

**Comment by amirfz** [comment]
@johnnykfeng yeah, there must be ways to add parameters that control the behavior of the bot. you can even trying asking sherpa itself haha

**Comment by johnnykfeng** [comment]
I've pushed some code changes, I suggest @saminegash, @20001LastOrder , or @YujingYang666777 review the PR. Basically it detects the string "-verbose" in the user message and adds the thought process to the final response.
