### ISSUE TITLE
redact pii (slack user names) from the data before indexing

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/practical-llms#33]
**Description:**
The data we scrape from various sources, for example slack, might contain personally identifiable information (pii). We need to redact this information before storing it. This is to preserve the privacy of the members of our community as well as future users of our tool. Examples of this might be user names.

**Steps to Reproduce:**
N/A

**Observation:** 
Information stored in our databases and sent to open ai might contain PII

Possible Solutions:
- step 1: research what kind of PII we should be careful about
- step 2: find out how other projects deal with PII (removal, replacement, ...)
- step 3: provide a plan 
- step 4: discuss and finalize the plan
- step 5: implement 

**Steps Taken So Far:**
N/A.

**Environment:**
N/A.

**Comment by Eyobyb** [comment]
can you explain this one

**Comment by amirfz** [comment]
@Eyobyb I added details

**Comment by Eyobyb** [comment]
I couldn't find a straightforward fix to redact PII. But there are services that provide removal.  From my search, I found the list of things we should try to avoid collecting to be in accordance with the General Data Protection Regulation (GDPR).

- Racial or ethnic origin
- Political opinions
- Religious or philosophical beliefs
- Trade union membership
- Genetic data
- Biometric data for the purpose of uniquely identifying a natural person
- Data concerning health or a natural person’s sex life and/or sexual orientation
- Name
- Physical Address
- Email Address
- Phone Number
- Credit Card Details
- Bank Details
- IP Address
- Date of Birth
- Employment Info
- Social Security Number
- Medical Information
- Individual’s picture/video/audio

**Comment by amirfz** [comment]
there's a realistically affordable solution for this on AWS marketplace: https://aws.amazon.com/marketplace/seller-profile?id=765aac32-1dce-45dc-8594-f13fa4cb61ec

closing this issue for now
