### ISSUE TITLE
styling of links

### ISSUE THREAD

**Issue by amirfz** [Aggregate-Intellect/practical-llms#37]
we're using markdown styling that slack doesn't understand. looks like the URLs should be formatted like this? could we quickly change that? note how the links are set up using <> instead of []

{
  "type": "section",
  "text": {
    "type": "mrkdwn",
    "text": "New Paid Time Off request from <[example.com](http://example.com/)|Fred Enriquez>\n\n<https://example.com/|View request>"
  }
}

**Comment by marija-stanojevic** [comment]
@amirfz You can assign this to me

**Comment by amirfz** [comment]
Marija is wokring on this still and will submit a PR tonight
