### ISSUE TITLE
rename some files in doc to remove colon

### ISSUE THREAD

**Issue by johnnykfeng** [Aggregate-Intellect/practical-llms#39]
When I try to clone the repo, it gives me this error:
`error: invalid path 'docs/LLM Foundations/Research Papers/Auto GPT: A Breakthrough in Language Models and Machine Learning Research.rst'`

The reason is because the colon in the filename causes an error in UNIX language. Can we rename these files? Just replace colon : with a dash -. Most of the problems are in this folder `docs/LLM Foundations/Research Papers`

**Comment by 20001LastOrder** [comment]
Resolved by #43 #44 #45
