### ISSUE TITLE
Create a `/verbose` slash command in the slackbot to show the thought process

### ISSUE THREAD

**Issue by johnnykfeng** [Aggregate-Intellect/practical-llms#61]
I notice people rarely use the `-verbose` flag. Sometimes I just want to see the thought process after the query, and I don't want to run the query again just to include -verbose. Having a function that reveals the thought process after the query reduces that friction.

I found a tutorial for creating slash commands, it seems simple enough.
https://www.youtube.com/watch?v=sEFx0b9y_Xo&list=PLzMcBGfZo4-kqyzTzJWCV6lyK-ZMYECDc&index=3

**Comment by 20001LastOrder** [comment]
Does this mean we need to store the thought process somewhere else than the slack chat history?

**Comment by amirfz** [comment]
well, `-verbose` is not expected to be used a lot since it's (atm) mostly for debugging purposes. the second part is interesting though. what info would you be looking for when you want to explore the "thought" process? like what's your objective? @johnnykfeng

**Comment by amirfz** [comment]
@johnnykfeng i feel like this might be easiest to discuss during our next call. will you be able to join the one on Tues?

**Comment by johnnykfeng** [comment]
@amirfz Sure, what time on Tuesday?

**Comment by amirfz** [comment]
noon. you should have a calendar invite
