### ISSUE TITLE
Choose and customize a better styling for converting to readthedoc

### ISSUE THREAD

**Issue by babasahebpinjar** [Aggregate-Intellect/practical-llms#8]
change the https://www.sphinx-doc.org/en/master/ styling to a more readable one

The formatting looks good, you may change the font to Bold for the topic headings mentioned below. 

KNOWLEDGE-OPS
LARGE LANGUAGE MODEL AGENTS - ONSET AGI?
LLM-OPS, ENGINEERING, AND ENTERPRISE CONSIDERATIONS
RISK MITIGATION OF LARGE LANGUAGE MODELS
LLM HANDS ON TUTORIALS AND RESOURCES
THEORETICAL FOUNDATIONS OF LARGE LANGUAGE MDOELS

**Comment by amirfz** [comment]
switched from the default template to "awesome" template. needed to pip install the package and add requirement.txt to include it during the build
